### ISSUE TITLE
GG了吗？

### ISSUE THREAD

**Issue by Helica-core** [hansnow/bupt-pingjiao#1]
点击后没反应，chrome报了这个错

VM1012:1 GET http://hann.sinaapp.com/static/pingjiao.js?ts=1467540446071 (anonymous function) @ VM1012:1(anonymous function) @ VM1012:1
空间挂掉了？

**Comment by hansnow** [comment]
由于原来的hann.sinaapp.com域名失效导致的404问题。现在问题已经修复，请删除原有书签并到 http://hansnow.github.io/pingjiao/ 重新添加。如果使用上有其他问题可以留言。
